import { Hero } from '@/components/hero/Hero'
import './globals.css'
import { Bai_Jamjuree, Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { Header } from '@/components/shared/Header'
import { ContentHeader } from '@/components/shared/ContentHeader'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '700'],
})

const baiJamjuree = Bai_Jamjuree({
  subsets: ['latin'],
  variable: '--font-baiJamjuree',
  weight: ['700'],
})

export const metadata = {
  title: 'Gustavo Dias - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${baiJamjuree.variable} bg-dark-main font-sans text-light-main`}
      >
        {/* Container */}
        <div className="relative max-h-screen lg:overflow-y-hidden">
          {/* Blur */}
          <div className="-left absolute -left-[263px] top-1/2 h-[288px] w-[526px] -translate-y-1/2 translate-x-0 rounded-full bg-dark-light opacity-50 blur-full" />

          {/* Main */}
          <div className="relative md:min-h-screen">
            <Header />

            <main className="mx-auto grid grid-cols-1 px-4 lg:max-w-screen-xl lg:grid-cols-2 lg:px-0">
              {/* Left */}
              <div className="-mt-16 lg:h-full lg:overflow-hidden">
                <Hero />
              </div>

              {/* Right */}
              <div className="flex flex-col gap-8 pt-8 md:max-h-screen lg:overflow-y-auto">
                <ContentHeader />
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
