import { Hero } from '@/components/hero/Hero'
import './globals.css'
import { Bai_Jamjuree, Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { Header } from '@/components/shared/Header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '700'],
})

const baiJamjuree = Bai_Jamjuree({
  subsets: ['latin'],
  variable: '--font-baiJamjuree',
  weight: ['700'],
})

export const metadata = {
  title: 'Gustavo Dias - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${baiJamjuree.variable} bg-dark-main font-sans text-light-main`}
      >
        {/* Container */}
        <div className="relative max-h-screen">
          {/* Blur */}
          <div className="-left absolute -left-[263px] top-1/2 h-[288px] w-[526px] -translate-y-1/2 translate-x-0 rounded-full bg-dark-light opacity-50 blur-full" />

          <Header />

          {/* Main */}
          <main className="relative grid sm:grid-cols-1 md:min-h-screen md:grid-cols-2">
            {/* Left */}
            <div className="flex pt-32 md:pt-16">
              <Hero />
            </div>

            {/* Right */}
            <div className="overflow-y-auto px-8 py-16 md:max-h-screen md:py-32 md:pr-32">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  )
}
